- name: init
  hosts: all
  become: yes
  tasks:
      - name: install pkgs
        apt:
            name:
                - wget
                - htop
                - nginx
            state: present
            update_cache: yes
      - name: start nginx
        service:
          name: nginx
          state: started
          enabled: yes
      - name: show env info
        debug:
            msg: "This host is in {{ ansible_hostname}} environment"
